random_seed = 1

[volume]
resolution = [40, 16, 16]

[model]
input_fov_shape = [13, 33, 33]
output_fov_shape = [13, 33, 33]
output_fov_move_fraction = 4
v_true = 0.95
v_false = 0.05
t_move = 0.9
move_check_thickness = 1
move_recheck = true

[network]
factory = 'diluvian.network.make_flood_fill_unet'
num_modules = 8
convolution_dim = [3, 3, 3]
convolution_filters = 32
output_activation = "sigmoid"
initialization = "glorot_uniform"
dropout_probability = 0.05
unet_num_layers = 4
unet_downsample_rate = [0, 1, 1]

[optimizer]
klass = "SGD"
lr = 0.001
momentum = 0.5
nesterov = true

[training]
gpu_batch_size = 32
num_gpus = 1
num_workers = 4
training_size = 1024
validation_size = 128
static_train_epochs = 0
total_epochs = 2
reset_generators = false
# fill_factor_bins = [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.075,
#                     0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
partitions = {".*" = [2, 1, 1]}
training_partition = {".*" = [0, 0, 0]}
validation_partition = {".*" = [1, 0, 0]}
patience = 20
augment_mirrors = [0, 1, 2]
augment_permute_axes = [[0, 2, 1]]
augment_missing_data = [{axis = 0, prob = 0.01}]
augment_noise = [{axis = 0, mul = 0.1, add = 0.1}]
augment_contrast = [{axis = 0, prob = 0.05, scaling_mean = 0.5, scaling_std = 0.1, center_mean = 1.2, center_std = 0.2}]

[postprocessing]
